Fix blank consent recordings
lookit/ember-lookit-frameplayer pull request #388
Opened 2024-05-28 23:58 UTC by becky-gilbert

Fixes #387

## Summary

This PR fixes the problem with blank consent videos by doing the following:
1. Disabling the 'start recording' button when the video consent page first loads, so that it only becomes enabled when the recorder is ready.
2. Requiring the 'recorderReady' property to be true before enabling the 'start recording' button. 

## Testing steps

- Create a study that starts with a video consent frame (so that the recorder takes longer to initialize). 
- As soon as the start recording button appears, immediately start clicking it and continue until the recording actually starts. 
- After the recording starts, stop the recording, and then click the replay button. You should see the video replay on the page (not a black screen). You should not be able to continue through the study until you play the recording.

To prolong the recording set-up time, you can also remove the video recording permissions for the site that are saved in your browser settings so that you're asked for recording permission when the page loads. The 'start recording' button should remain disabled until you after you give permission for the page to record.

We need to repeat these tests in Chrome and Firefox.

2024-05-30 21:23 UTC, ianchandlercampbell requested changes
@becky-gilbert I think this is a good solution overall! I worry a bit about asking them to re-approve recording permissions because sometimes those behave a bit erratically on browsers (this has gotten better in recent experience but still wary from times in the past where I had trouble getting a site to display the option to give permission). I'd lean towards leaving that out and only doing the Start Recording button disable, but open to discuss this!

2024-05-30 21:32 UTC, becky-gilbert commented
@ianchandlercampbell oh sorry, I totally agree and I'm not actually requiring the user to re-approve permissions! I only disabled my own permissions for testing purposes, and so that the page stayed in the 'not ready to record' state for long enough for me to take a screenshot. The permissions will work exactly the same as before.

2024-05-30 21:35 UTC, becky-gilbert commented
Hmm, I edited the PR description to include a lot more detail and screenshots, but for some reason my updates are gone :( I'll update it again ASAP to reflect what I've actually done.

2024-05-30 22:50 UTC, ianchandlercampbell commented
Oh sorry @becky-gilbert I clearly read too fast! I see that's part of testing

2024-06-05 14:24 UTC, okaycj approved these changes
LGTM!

2024-06-05 17:25 UTC, merged