Moving changes to to master branch.
lookit/ember-lookit-frameplayer pull request #390
Opened 2024-05-30 17:09 UTC by okaycj

2024-05-30 17:40 UTC, becky-gilbert requested changes
Ohh, actually I'm retracting my approval because I just remembered that EFP docs are in this same repository. So it makes sense to include them with the release.

2024-06-03 22:06 UTC, becky-gilbert approved these changes
LGTM 🚀

2024-06-04 18:14 UTC, bleonar5 approved these changes

2024-06-05 18:21 UTC, merged

2024-06-05 19:58 UTC, ianchandlercampbell commented
Did some editing and formatting to prep this for the EFP release page! @becky-gilbert feel free to edit/revise further!